title: 'Welcome to Febin\'s Portfolio'
email: Febin_portfolio32@gmail.com
description: "A showcase of my data science projects and skills."
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://yourwebsite.com" # the base hostname & protocol for your site

# Social links
social:
  github: "https://github.com/yourusername"
  #linkedin: "https://www.linkedin.com/in/yourprofile/"
  #twitter: "https://twitter.com/yourusername"

# Build settings
markdown: kramdown
theme: minima # or any theme you prefer

