title: 'Welcome to Febin\'s Portfolio'
email: Febin_portfolio32@gmail.com
description: "A showcase of my data science projects and skills."
markdown: kramdown
theme: minima # or any theme you prefer

